/**
 * STOCK PHRASES — the data behind stock.ts.
 *
 * Derived from the over-represented-phrase list in sam-paech/antislop-sampler
 * (slop_phrases_2025-04-07.json), Copyright Sam Paech, licensed under the Apache License,
 * Version 2.0 (http://www.apache.org/licenses/LICENSE-2.0). That list ranks phrases by how much
 * more often language models write them than human writers do, measured over a large corpus of
 * model-written fiction.
 *
 * CHANGES MADE HERE: the top 600 entries were taken; each was lowercased, stripped of
 * punctuation, and had its pronouns folded to POSS / SUBJ / OBJ so one entry covers "her chest",
 * "his chest" and "your chest"; duplicates were merged with their counts summed; and entries that
 * are ordinary concrete action ("took a step back", "pushed the door open"), place furniture
 * ("corrugated iron roof"), names the source corpus over-used ("Elara") or noise were removed.
 * STOCK_BANS is the raw, un-folded form of the top 400 after the same removals, for samplers that
 * ban literal strings.
 */

/** Folded phrases, most over-used first. Matched by stock.ts against folded text. */
export const STOCK_PHRASES: readonly string[] = [
  "took a deep breath",
  "voice barely above a whisper",
  "couldn't help but feel",
  "heart pounding in POSS chest",
  "said POSS voice barely",
  "help but feel a sense",
  "voice barely audible",
  "casting long shadows",
  "asked POSS voice barely",
  "voice barely a whisper",
  "couldn't shake the feeling",
  "couldn't help but wonder",
  "long shadows across",
  "said POSS voice steady",
  "said POSS voice low",
  "sun dipped below the horizon",
  "chill run down POSS spine",
  "felt a chill run",
  "days turned into weeks",
  "air was thick with the scent",
  "smile playing on POSS lips",
  "whispered POSS voice barely",
  "felt like an eternity",
  "shiver run down POSS spine",
  "voice steady despite",
  "spreading across POSS face",
  "felt a shiver run",
  "breath caught in POSS throat",
  "taking a deep breath",
  "room fell silent",
  "ready to face whatever",
  "heart pounded in POSS chest",
  "trying to make sense",
  "dipped below the horizon casting",
  "said POSS voice filled",
  "deep breath trying",
  "felt a strange sense",
  "something else entirely",
  "could feel the weight",
  "words hung in the air",
  "said POSS voice trembling",
  "asked POSS voice trembling",
  "said POSS voice firm",
  "brow furrowed in concentration",
  "voice trembling slightly",
  "door creaked open",
  "eyes never leaving",
  "voice a low rumble",
  "growing sense of unease",
  "heart skipped a beat",
  "air hung thick",
  "sun hung low",
  "casting a warm glow",
  "sent a shiver down POSS spine",
  "renewed sense of purpose",
  "horizon casting long",
  "hung low in the sky",
  "smile spreading across",
  "low in the sky casting",
  "hung heavy in the air",
  "eyes wide with fear",
  "shake the feeling that something",
  "something else something",
  "face whatever challenges",
  "spread like wildfire",
  "road ahead would",
  "felt a sense of peace",
  "newfound sense of purpose",
  "grin spreading across",
  "eyes filled with a mixture",
  "said POSS voice a low",
  "flicker of something akin",
  "eyes locked onto",
  "dimly lit room",
  "tried to make sense",
  "challenges lay ahead",
  "hung in the air heavy",
  "eyes darting around",
  "couldn't help but notice",
  "deep breath steeling",
  "said POSS voice soft",
  "brow furrowed in confusion",
  "said POSS voice laced",
  "leaned forward POSS eyes",
  "would find a way",
  "fingers flying across",
  "eyes wide with wonder",
  "dust motes danced",
  "mind raced trying",
  "figure emerged from the shadows",
  "heart hammered against POSS ribs",
  "felt a strange sensation",
  "small smile playing",
  "trying to keep POSS voice",
  "felt a cold dread",
  "hung thick with the scent",
  "air was thick with tension",
  "sky casting long",
  "would never forget",
  "whatever challenges lay",
  "mind racing with questions",
  "said trying to sound",
  "unlike anything SUBJ had ever",
  "gaze sweeping across",
  "said POSS voice dripping",
  "resonated deep within",
  "first time in a long",
  "blood ran cold",
  "deep breath feeling",
  "mind racing with the implications",
  "mind racing with possibilities",
  "eyes widened in surprise",
  "eyes wide with a mixture",
  "could find a way",
  "said POSS voice tinged",
  "air thick with the scent",
  "eyes scanning the room",
  "felt a growing sense",
  "help but feel a twinge",
  "smile spread across",
  "feel a sense of unease",
  "scent of damp earth",
  "growing sense of dread",
  "asked POSS voice laced",
  "raised a hand silencing",
  "began to set casting",
  "sighed running a hand",
  "hand instinctively reaching",
  "sense of peace wash",
  "heart heavy with the weight",
  "said POSS voice calm",
  "knew that the road ahead",
  "smile tugging at the corners",
  "keep POSS voice steady",
  "knuckles turning white",
  "felt a glimmer of hope",
  "cast long shadows",
  "eyes widened in shock",
  "air grew thick",
  "feel a sense of pride",
  "horizon painting the sky",
  "faint almost imperceptible",
  "breath catching in POSS throat",
  "continued to fall washing",
  "casting an eerie glow",
  "ahead would be long",
  "knew with a chilling certainty",
  "eyes locking onto",
  "voice thick with emotion",
  "mind already racing",
  "air was thick with anticipation",
  "said trying to keep",
  "find a way to break",
  "long dancing shadows",
  "casting a golden glow",
  "whispered POSS voice trembling",
  "needed to find a way",
  "change the course of history",
  "couldn't quite place",
  "eyes wide with terror",
  "would change the course",
  "need to find a way",
  "sent shivers down POSS spine",
  "find a way to make",
  "painting the sky in hues",
  "eyes wide with disbelief",
  "air grew colder",
  "time in a long time",
  "began to take shape",
  "life would never",
  "small almost imperceptible",
  "eyes filled with tears",
  "one thing was certain",
  "challenges that lay ahead",
  "whatever lay ahead",
  "could feel the power",
  "shiver ran down POSS spine",
  "like a physical blow",
  "chill ran down POSS spine",
  "couldn't help but smile",
  "set casting long",
  "horizon casting a warm",
  "voice tinged with a hint",
  "like a second skin",
  "shook POSS head trying",
  "asked trying to keep",
  "eyes darted around",
  "could almost hear",
  "tasting like ash",
  "darting around the room",
  "exchanged uneasy glances",
  "mix of excitement and trepidation",
  "fingers dancing across",
  "heart pounding with a mixture",
  "felt like hours",
  "felt a flicker of hope",
  "felt a surge of energy",
  "blinding flash of light",
  "wave of nausea washed",
  "senses on high alert",
  "deep breath and stepped",
  "blood run cold",
  "brow furrowed with concern",
  "warm golden glow",
  "heart skip a beat",
  "air hung heavy",
  "seemed to hold POSS breath",
  "air crackled with energy",
  "mind racing with a thousand",
  "locked onto mine",
  "felt a surge of anger",
  "voice devoid of emotion",
  "breath trying to steady",
  "world held POSS breath",
  "dancing shadows across",
  "dimly lit chamber",
  "hung in the air like",
  "watched in stunned silence",
  "course of human history",
  "steady despite the turmoil",
  "strange sense of peace",
  "question hung in the air",
  "felt a sense of purpose",
  "would do whatever it took",
  "breath trying to calm",
  "sound like wind",
  "dipped below the horizon painting",
  "faces etched with a mixture",
  "one thing was clear",
  "nodded POSS mind racing",
  "finally after what felt like",
  "something far more sinister",
  "air was thick with the smell",
  "like polished obsidian",
  "couldn't help but think",
  "faint smile playing",
  "stumbled upon something",
  "mixture of excitement and trepidation",
  "help but wonder what the future",
  "felt a profound sense",
  "casting a golden hue",
  "trying to piece together",
  "find a way to stop",
  "voice low and urgent",
  "spread across POSS face",
  "cold dread creep",
  "would stop at nothing",
  "eyes wide with shock",
  "face whatever lay",
  "would change everything",
  "moon hung low",
  "chuckled a sound like",
  "couldn't quite put",
  "raised an eyebrow intrigued",
  "smile playing at the corners",
  "gaze fell upon",
  "felt a pang of guilt",
  "creaked open revealing",
  "could feel the tension",
  "felt a flicker of something",
  "silent for a long moment",
  "face whatever came",
  "felt a surge of power",
  "fingers trembling slightly",
  "collective gasp rippled",
  "casting eerie shadows",
  "sense of relief wash",
  "relic of a bygone era",
  "eyes filled with a mix",
  "words echoed in POSS mind",
  "words caught in POSS throat",
  "wide with a mixture of fear",
  "low resonant hum",
  "couldn't help but marvel",
  "could change the course",
  "fingers danced across",
  "felt a surge of hope",
  "panic clawed at POSS throat",
  "hands trembling slightly",
  "eyes widened in horror",
  "strange tingling sensation",
  "could have ever imagined",
  "word hung in the air",
  "feel a growing sense",
  "let out a shaky breath",
  "mixture of fear and determination",
  "almost too much to bear",
  "felt less like",
  "carefully constructed facade",
  "walked away leaving",
  "nothing could have prepared",
  "mouth suddenly dry",
  "rain intensified drumming",
  "voice laced with a hint",
  "world a better place",
  "long shadows that danced",
  "figure stepped forward",
  "sound that sent shivers",
  "like wind chimes",
  "dust motes dancing",
  "could change everything",
  "heart pounding with a mix",
  "wonder what the future held",
  "nodded feeling a sense",
  "flying across the keyboard",
  "like distant thunder",
  "thick with the scent of damp",
  "voice a low growl",
  "eyes widened in disbelief",
  "casting a warm golden",
  "sun dipped low",
  "subtle almost imperceptible",
  "make sense of what was happening",
  "something felt different",
  "voice gaining strength",
  "turned into weeks and the weeks",
  "shadows across the room",
  "laughed a sound like",
  "eyes scanning the horizon",
  "voice dropping to a conspiratorial",
  "feel a sense of excitement",
  "could almost feel",
  "like ash in POSS mouth",
  "thought sent a shiver",
  "filled with a mixture of fear",
  "like molten gold",
  "never leaving mine",
  "make sense of the situation",
  "seemed to absorb the light",
  "words tasting like",
  "felt a surge of determination",
  "brow furrowed in thought",
  "beacon of hope in a world",
  "forge a new path",
  "room was dimly lit",
  "shadows that danced across",
  "voice low and menacing",
  "help but feel a growing",
  "felt a deep sense",
  "journey ahead would",
  "raced trying to make",
  "hanging heavy in the air",
  "air was thick with the stench",
  "exchanged nervous glances",
  "long as SUBJ could remember",
  "took a tentative step",
  "strange sense of calm",
  "voice dripping with sarcasm",
  "something unexpected happened",
  "something deep within",
  "determined to uncover the truth",
  "sun was setting casting",
  "uncover the truth behind",
  "weeks and the weeks into months",
  "gaze locked onto",
  "part of something greater",
  "help but feel a pang",
  "said POSS voice smooth",
  "felt a renewed sense",
  "sense of unease settled",
  "hammered against POSS ribs a frantic",
  "steady despite the tremor",
  "wave of dizziness washed",
  "could see the fear",
  "hush fell over the crowd",
  "voice low and dangerous",
  "ribs a frantic drumbeat",
  "moment SUBJ thought SUBJ saw",
  "felt a surge of panic",
  "painting the sky with hues",
  "sky in hues of orange",
  "felt a surge of adrenaline",
  "felt a surge of pride",
  "ahead would be fraught",
  "tasted like ash",
  "hint of a smile playing",
  "sent a chill down POSS spine",
  "feel a sense of awe",
  "buried deep within",
  "flicker of movement caught",
  "change the course of human",
  "heart pounding with anticipation",
  "felt a sense of relief",
  "throat suddenly dry",
  "asked POSS voice low",
  "voice dripping with malice",
  "dropping to a conspiratorial whisper",
  "voice calm and measured",
  "said forcing a smile",
  "tears streaming down POSS face",
  "eyes met mine",
  "motes danced in the single",
  "mixture of awe and trepidation",
  "heart hammering against POSS ribs",
  "freshly baked bread",
  "weeks turned into months",
  "swallowed hard trying",
  "mind racing as SUBJ tried",
  "voice surprisingly steady",
  "movements fluid and graceful",
  "heart of the bustling city",
  "one thing for certain",
  "inside the air was thick",
  "door slammed shut",
  "couldn't wait to see",
  "felt a wave of nausea",
  "sun had barely risen",
  "mind racing with thoughts",
  "eyes meeting mine",
  "ground beneath POSS feet",
  "long distorted shadows",
  "eye could see",
  "wrap POSS head around",
  "flickered to life displaying",
  "like a tidal wave",
  "could feel the energy",
  "looked suspiciously like",
  "chapter based on the provided",
  "eyes widening in surprise",
  "deep breath and began",
  "swung POSS legs over the side",
  "squeezed POSS eyes shut",
  "coming in ragged gasps",
  "grin spread across",
  "flickering fluorescent lights",
  "make the world a better",
  "knew that SUBJ would never",
  "must find a way",
  "sighed a sound like",
  "door slid open",
  "fingers tracing the intricate",
  "casting dancing shadows",
  "line went dead",
  "felt a cold sweat",
  "life support systems",
  "far as the eye could",
  "voice laced with concern",
  "replied POSS voice steady",
  "darted around the room",
  "brow furrowing in confusion",
  "power of the human spirit",
  "eyes darting nervously",
  "hues of orange and purple",
  "felt a strange connection",
  "would forever change",
  "mind racing with the possibilities",
  "casting long dancing",
  "voice steady and resolute",
  "breath coming in ragged",
  "felt a wave of relief",
  "whispered in hushed tones",
  "made the right choice",
  "crowd fell silent",
  "surge of energy coursing",
  "couldn't help but chuckle",
  "stepped forward POSS voice",
  "danced in the single shaft",
  "man whose face",
  "stars began to twinkle",
  "force of a physical blow",
  "eyes sparkling with mischief",
  "stammered POSS voice barely",
  "metallic tang of blood",
  "said voice steady",
  "head trying to clear",
  "like dry leaves",
  "voice a low resonant",
  "small smile tugging",
  "feeling a strange sense",
  "trying to sound casual",
  "made a terrible mistake",
  "sudden gust of wind",
  "face pale and drawn",
  "something vaguely metallic",
  "sun had long since",
  "like a living thing",
  "panic began to set",
  "low guttural growl",
  "wave of relief wash",
  "thick with the scent of old",
  "run down POSS spine as SUBJ realized",
  "unexpected turn of events",
  "adorned with intricate carvings",
  "first time in centuries",
  "fingers tightened around",
  "stepped forward POSS eyes",
  "whispers grew louder",
  "mix of fear and determination",
  "voice low and gravelly",
  "face etched with worry",
];

/** Literal phrases for a sampler-side ban (KoboldCpp banned_strings). */
export const STOCK_BANS: readonly string[] = [
  "took a deep breath",
  "voice barely above a whisper",
  "couldn't help but feel",
  "help but feel a sense",
  "voice barely audible",
  "casting long shadows",
  "voice barely a whisper",
  "couldn't shake the feeling",
  "couldn't help but wonder",
  "long shadows across",
  "heart pounding in my chest",
  "sun dipped below the horizon",
  "felt a chill run",
  "air was thick with the scent",
  "felt like an eternity",
  "heart pounding in her chest",
  "voice steady despite",
  "felt a shiver run",
  "said, his voice low",
  "room fell silent",
  "ready to face whatever",
  "trying to make sense",
  "said, his voice barely",
  "dipped below the horizon, casting",
  "said, her voice barely",
  "asked, my voice barely",
  "deep breath, trying",
  "felt a strange sense",
  "something else entirely",
  "could feel the weight",
  "words hung in the air",
  "heart pounding in his chest",
  "brow furrowed in concentration",
  "smile playing on his lips",
  "voice trembling slightly",
  "asked, her voice barely",
  "door creaked open",
  "eyes never leaving",
  "days turned into weeks",
  "voice a low rumble",
  "growing sense of unease",
  "heart skipped a beat",
  "air hung thick",
  "said, her voice steady",
  "sun hung low",
  "shiver run down my spine",
  "said, my voice barely",
  "casting a warm glow",
  "renewed sense of purpose",
  "spreading across his face",
  "taking a deep breath",
  "horizon, casting long",
  "hung low in the sky",
  "whispered, her voice barely",
  "smile spreading across",
  "low in the sky, casting",
  "hung heavy in the air",
  "eyes wide with fear",
  "shake the feeling that something",
  "something else, something",
  "face whatever challenges",
  "spread like wildfire",
  "asked, his voice barely",
  "road ahead would",
  "felt a sense of peace",
  "newfound sense of purpose",
  "grin spreading across",
  "eyes filled with a mixture",
  "said, his voice a low",
  "flicker of something akin",
  "eyes locked onto",
  "dimly lit room",
  "tried to make sense",
  "challenges lay ahead",
  "hung in the air, heavy",
  "chill run down my spine",
  "said, his voice filled",
  "eyes darting around",
  "said, his voice steady",
  "couldn't help but notice",
  "deep breath, steeling",
  "brow furrowed in confusion",
  "sent a shiver down my spine",
  "chill run down her spine",
  "would find a way",
  "breath caught in her throat",
  "fingers flying across",
  "eyes wide with wonder",
  "dust motes danced",
  "mind raced, trying",
  "figure emerged from the shadows",
  "heart hammered against my ribs",
  "felt a strange sensation",
  "small smile playing",
  "trying to keep my voice",
  "felt a cold dread",
  "hung thick with the scent",
  "air was thick with tension",
  "sky, casting long",
  "would never forget",
  "whatever challenges lay",
  "mind racing with questions",
  "said, trying to sound",
  "said, her voice trembling",
  "gaze sweeping across",
  "said, his voice dripping",
  "resonated deep within",
  "first time in a long",
  "blood ran cold",
  "deep breath, feeling",
  "mind racing with the implications",
  "mind racing with possibilities",
  "eyes widened in surprise",
  "said, her voice filled",
  "eyes wide with a mixture",
  "smile playing on her lips",
  "could find a way",
  "said, my voice steady",
  "air thick with the scent",
  "eyes scanning the room",
  "felt a growing sense",
  "asked, her voice trembling",
  "help but feel a twinge",
  "smile spread across",
  "breath caught in my throat",
  "heart pounded in my chest",
  "feel a sense of unease",
  "scent of damp earth",
  "growing sense of dread",
  "raised a hand, silencing",
  "began to set, casting",
  "sighed, running a hand",
  "hand instinctively reaching",
  "sense of peace wash",
  "heart heavy with the weight",
  "knew that the road ahead",
  "said, her voice soft",
  "smile tugging at the corners",
  "leaned forward, his eyes",
  "keep my voice steady",
  "knuckles turning white",
  "said, her voice firm",
  "felt a glimmer of hope",
  "heart pounded in her chest",
  "cast long shadows",
  "eyes widened in shock",
  "air grew thick",
  "feel a sense of pride",
  "horizon, painting the sky",
  "whispered, his voice barely",
  "faint, almost imperceptible",
  "said, his voice firm",
  "continued to fall, washing",
  "casting an eerie glow",
  "ahead would be long",
  "knew, with a chilling certainty",
  "eyes locking onto",
  "voice thick with emotion",
  "mind already racing",
  "air was thick with anticipation",
  "said, trying to keep",
  "find a way to break",
  "long, dancing shadows",
  "casting a golden glow",
  "chill run down his spine",
  "whispered, her voice trembling",
  "needed to find a way",
  "change the course of history",
  "couldn't quite place",
  "eyes wide with terror",
  "would change the course",
  "need to find a way",
  "sent shivers down my spine",
  "asked, my voice trembling",
  "find a way to make",
  "painting the sky in hues",
  "eyes wide with disbelief",
  "air grew colder",
  "said, her voice low",
  "time in a long time",
  "began to take shape",
  "life would never",
  "said, his voice laced",
  "small, almost imperceptible",
  "eyes filled with tears",
  "one thing was certain",
  "challenges that lay ahead",
  "whatever lay ahead",
  "could feel the power",
  "shiver ran down my spine",
  "like a physical blow",
  "chill ran down my spine",
  "couldn't help but smile",
  "set, casting long",
  "horizon, casting a warm",
  "voice tinged with a hint",
  "shiver run down her spine",
  "like a second skin",
  "shook my head, trying",
  "asked, trying to keep",
  "eyes darted around",
  "could almost hear",
  "tasting like ash",
  "darting around the room",
  "exchanged uneasy glances",
  "mix of excitement and trepidation",
  "fingers dancing across",
  "heart pounding with a mixture",
  "felt like hours",
  "felt a flicker of hope",
  "felt a surge of energy",
  "blinding flash of light",
  "heart pounded in his chest",
  "wave of nausea washed",
  "senses on high alert",
  "deep breath and stepped",
  "blood run cold",
  "brow furrowed with concern",
  "warm, golden glow",
  "heart skip a beat",
  "air hung heavy",
  "seemed to hold its breath",
  "air crackled with energy",
  "mind racing with a thousand",
  "locked onto mine",
  "felt a surge of anger",
  "voice devoid of emotion",
  "breath, trying to steady",
  "world held its breath",
  "dancing shadows across",
  "dimly lit chamber",
  "hung in the air like",
  "watched in stunned silence",
  "course of human history",
  "steady despite the turmoil",
  "strange sense of peace",
  "question hung in the air",
  "felt a sense of purpose",
  "would do whatever it took",
  "breath, trying to calm",
  "sound like wind",
  "said, his voice trembling",
  "dipped below the horizon, painting",
  "faces etched with a mixture",
  "one thing was clear",
  "nodded, her mind racing",
  "finally, after what felt like",
  "something far more sinister",
  "air was thick with the smell",
  "like polished obsidian",
  "couldn't help but think",
  "faint smile playing",
  "stumbled upon something",
  "mixture of excitement and trepidation",
  "help but wonder what the future",
  "felt a profound sense",
  "casting a golden hue",
  "said, his voice tinged",
  "spreading across her face",
  "trying to piece together",
  "find a way to stop",
  "voice low and urgent",
  "whispered, my voice barely",
  "spread across his face",
  "cold dread creep",
  "would stop at nothing",
  "eyes wide with shock",
  "face whatever lay",
  "would change everything",
  "moon hung low",
  "chuckled, a sound like",
  "couldn't quite put",
  "raised an eyebrow, intrigued",
  "smile playing at the corners",
  "gaze fell upon",
  "felt a pang of guilt",
  "unlike anything i had ever",
  "creaked open, revealing",
  "could feel the tension",
  "felt a flicker of something",
  "silent for a long moment",
  "said, my voice trembling",
  "face whatever came",
  "felt a surge of power",
  "fingers trembling slightly",
  "collective gasp rippled",
  "casting eerie shadows",
  "sense of relief wash",
  "relic of a bygone era",
  "eyes filled with a mix",
  "words echoed in my mind",
  "words caught in my throat",
  "said, my voice firm",
  "wide with a mixture of fear",
  "low, resonant hum",
  "couldn't help but marvel",
  "could change the course",
  "fingers danced across",
  "felt a surge of hope",
  "panic clawed at my throat",
  "hands trembling slightly",
  "eyes widened in horror",
  "said, her voice laced",
  "strange tingling sensation",
  "could have ever imagined",
  "word hung in the air",
  "feel a growing sense",
  "let out a shaky breath",
  "mixture of fear and determination",
  "almost too much to bear",
  "felt less like",
  "unlike anything she had ever",
  "carefully constructed facade",
  "walked away, leaving",
  "nothing could have prepared",
  "mouth suddenly dry",
  "rain intensified, drumming",
  "voice laced with a hint",
  "world a better place",
  "long shadows that danced",
  "figure stepped forward",
  "sound that sent shivers",
  "like wind chimes",
  "dust motes dancing",
  "could change everything",
  "heart pounding with a mix",
  "wonder what the future held",
  "nodded, feeling a sense",
  "flying across the keyboard",
  "like distant thunder",
  "thick with the scent of damp",
  "voice a low growl",
  "eyes widened in disbelief",
  "casting a warm, golden",
  "spreading across my face",
  "sun dipped low",
  "subtle, almost imperceptible",
  "make sense of what was happening",
  "something felt different",
];
